# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Seknova' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Seknova
  pod 'IQKeyboardManagerSwift', '6.5.10'
  pod 'RealmSwift', '10.33.0'

  target 'SeknovaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SeknovaUITests' do
    # Pods for testing
  end

end
